name: export-and-branch-solution-configuration
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: MyTimeApp
      #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: src/out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: src/out/solutions/
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: src/solutions/
      commit-comment: 
       description: 'Your commit comment'
       required: true

permissions:
  contents: write
jobs:
  export-solution-from-dev:
    runs-on: windows-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Power Platform Action Install
      uses: microsoft/powerplatform-actions/actions-install@v1.2.0
      with:
        pac-version-override: 1.29.11

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v1.2.0
      with:
        environment-url: ${{vars.ENVIRONMENT_URL}}
        app-id: ${{vars.CLIENT_ID}}
        client-secret: ${{secrets.SPN}}
        tenant-id: ${{vars.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        managed: true
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v1.2.0
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Managed'
        overwrite-files: true
        
    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v1.2.0
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
        
